source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'AmpiriSDKDemoApp'
target 'AmpiriSDKDemoApp' do
  pod 'ampiri-ios-sdk', '~> 3.3.0'

end

target 'AmpiriSDKDemoAppSwift' do
  pod 'ampiri-ios-sdk', '~> 3.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
