source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.glispa.com:ampiri/Specs.git'

platform :ios, '8.0'

workspace 'AmpiriSDKDemoApp'
target 'AmpiriSDKDemoApp' do
  pod 'ampiri-ios-dev', '~> 3.2.1-100'

end

target 'AmpiriSDKDemoAppSwift' do
  pod 'ampiri-ios-dev', '~> 3.2.1-100'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
